# mlflow and min.io s3 model artifact store

version: "3.8"

services:
  db:
    container_name: mlflow_db
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  minio:
    container_name: mlflow_s3
    image: minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ADMIN_PASSWORD}
      MINIO_STORAGE_USE_HTTPS: "false"
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: >
      server /data
      --console-address ':9001'
      --address ':9000'

  mlflow:
    container_name: mlflow_server
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - minio
      - db
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_IGNORE_TLS: "true"
    ports:
      - "${MLFLOW_PORT}:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://mlflow

volumes:
  pgdata:
  minio_data:
